### ISSUE TITLE
llava 1.5 textvqa baseline 为何如此低？

### ISSUE THREAD

**Issue by hhaAndroid** [bzluan/TextCoT#1]
如题，我看论文里面写的是 37.92，但是我看 llava 1.5 7b 官方写的是 58.2，为何差距如此之大？ 是数据集并不是同一个 textvqa 吗？

**Comment by bzluan** [comment]
In LLaVA's TextVQA evaluation, OCR data was incorporated into the textual questions. We conducted evaluation experiments according to MultimodalOCR (https://arxiv.org/abs/2305.07895) (https://github.com/Yuliang-Liu/MultimodalOCR). In their TextVQA evaluation dataset, OCR data wasn't utilized. Our baseline results are similar to those outlined in their paper.

**Comment by hhaAndroid** [comment]
@bzluan OK
