### ISSUE TITLE
No answer_format.json file!!!

### ISSUE THREAD

**Issue by orormaybe** [bzluan/TextCoT#3]
There is No answer_format.json file!!!

**Comment by Cyc-striving** [comment]
Did you find the answer_format.json file?

**Comment by orormaybe** [comment]
> Did you find the answer_format.json file?

The answer_format.json is a empty json file

**Comment by Cyc-striving** [comment]
> > Did you find the answer_format.json file?
> 
> The answer_format.json is a empty json file

Thanks
