### ISSUE TITLE
prepare_stage2_question.py cannot be found.

### ISSUE THREAD

**Issue by hanzefang** [bzluan/TextCoT#5]

**Comment by bzluan** [comment]
Thank you for your interest in our work. The prepare_stage2_question.py file corresponds to the second ablation experiment in the paper, which involves only the ground operation. In this experiment, the text-based answer from the Coarse Localization stage is directly incorporated into the prompt. While this result is not the final method presented in the paper, I have uploaded the prepare_stage2_question.py file to facilitate testing for everyone.

Let me know if this works for you!
